language: php
php:
    - 7.3
    - 7.4
    - 8.0
    
env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"

before_install: 
    pecl install apcu
    pecl install posix
    pecl install pcntl
    phpenv config-add tests/travis.ini
        
install:
    - travis_retry composer update ${COMPOSER_FLAGS}
    
script:
  - vendor/bin/phpunit --testdox tests